stages:
  - lint
  - test

run-python-linter:
  stage: lint
  image: pyfound/black:22.12.0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
  before_script:
    - black --version
  script:
    - black . --check


run-unit-tests:
  stage: test
  image: python:3.9
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
  before_script:
    - pip install .
  script:
    - pytest
